sudo: required
python:
  - "2.7"

# Clean and don't fail
install:
  - sudo pip install pygments
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.32.3/hugo_0.32.3_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
  - rm -rf public || exit 0

before_script:
  - git config --global user.email "edel.altares@gmail.com"
  - git config --global user.name "Edel-Travis"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials

# Build the website
script:
  - pygmentize -V
  - git branch
  - rm -rf public/*
  - git submodule update --init --recursive
  - hugo -v
  - cp CNAME public/

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  target-branch: master
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master