baseurl = "https://edelgrace.github.io/"
languageCode = "en-US"
title = "edel grace altares"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:section/:slug"

[params]
  avatar = "http://res.cloudinary.com/dvozrk6m8/image/upload/v1512463955/edel-altares_jcufrn.png"
  author = "Edel Grace Altares"
  description = "Here you can keep up with all of the various things I do."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "edelgrace"
  Email         = "edel.altares@gmail.com"
  Twitter       = "edelgraceme"
  LinkedIn      = "edel-altares"

## Main Menu
[[menu.main]]
  mame = "about"
  identifier = "about"
  weight = 100
  url = "/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/project/"
[[menu.main]]
  name = "blog"
  weight = 300
  identifier = "blog"
  url = "/blog/"