baseurl = "http://edelgrace.me/"
languageCode = "en-US"
title = "edel grace altares"
# Enable comments by entering your Disqus shortname
disqusShortname = "edelgrace"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "edel"

[permalinks]
  post = "/:section/:slug"

[params]
  avatar = "http://res.cloudinary.com/dvozrk6m8/image/upload/v1512463955/edel-altares_jcufrn.png"
  author = "Edel"
  description = "My name is **Edel Grace Altares**. My programming interests include **full stack development** and **back end development**. My languages of choice are **Python** and **Java**. Outside of programming I enjoy crocheting, video games, cats, historical fiction, and reading."